import{S as g,i as L}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const b="45040943-e695a2a5e7ee0373bf96f3099",S="https://pixabay.com/api/";let u=1;const q=15;async function f(e){const o=`${S}?key=${b}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${u}&per_page=${q}`,r=await fetch(o);if(!r.ok)throw new Error(`An error occurred: ${r.statusText}`);return await r.json()}function M(){u+=1}function w(){u=1}let l;function m(e){const o=document.querySelector(".gallery"),r=e.map(s=>$(s)).join("");o.insertAdjacentHTML("beforeend",r),l?l.refresh():l=new g(".gallery a")}function $({webformatURL:e,largeImageURL:o,tags:r,likes:s,views:t,comments:n,downloads:i}){return`
    <a href="${o}" class="gallery__item">
      <img src="${e}" alt="${r}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes</b> ${s}</p>
        <p class="info-item"><b>Views</b> ${t}</p>
        <p class="info-item"><b>Comments</b> ${n}</p>
        <p class="info-item"><b>Downloads</b> ${i}</p>
      </div>
    </a>
  `}function c(e){L.error({title:"Error",message:e,position:"topRight"})}function v(){document.querySelector(".load-more").classList.remove("hidden")}function a(){document.querySelector(".load-more").classList.add("hidden")}function d(){document.querySelector(".end-of-collection").classList.remove("hidden")}function B(){document.querySelector(".end-of-collection").classList.add("hidden")}function h(){const e=document.querySelector("#loader");e.style.display="block"}function y(){const e=document.querySelector("#loader");e.style.display="none"}const E=document.querySelector("#search-form"),p=document.querySelector("#search-input"),P=document.querySelector(".gallery"),O=document.querySelector(".load-more");E.addEventListener("submit",async e=>{e.preventDefault();const o=p.value.trim();if(o===""){c("Please enter a search term");return}w(),P.innerHTML="",B(),a(),h();try{const r=await f(o);r.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(m(r.hits),r.totalHits>15&&v(),r.totalHits<=15&&(a(),d()))}catch(r){c(r.message)}finally{y()}});O.addEventListener("click",async()=>{M(),h();try{const e=p.value.trim(),o=await f(e);o.hits.length===0?(a(),d()):(m(o.hits),_(),o.hits.length<15&&(a(),d()))}catch(e){c(e.message)}finally{y()}});function _(){const{height:e}=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:2*e,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
